/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpdatePasswordIndexRouteImport } from './routes/update-password/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as SignUpSuccessIndexRouteImport } from './routes/sign-up-success/index'
import { Route as MatchupsIndexRouteImport } from './routes/matchups/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as TournamentsTournamentIdRouteImport } from './routes/tournaments/$tournamentId'
import { Route as AdminTournamentsTournamentIdRouteImport } from './routes/admin/tournaments/$tournamentId'
import { Route as ProtectedAuthErrorRouteImport } from './routes/_protected/auth/error'
import { Route as ProtectedAuthConfirmRouteImport } from './routes/_protected/auth/confirm'
import { Route as ProtectedProtectedProtectedRouteImport } from './routes/_protected/_protected/protected'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePasswordIndexRoute = UpdatePasswordIndexRouteImport.update({
  id: '/update-password/',
  path: '/update-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSuccessIndexRoute = SignUpSuccessIndexRouteImport.update({
  id: '/sign-up-success/',
  path: '/sign-up-success/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchupsIndexRoute = MatchupsIndexRouteImport.update({
  id: '/matchups/',
  path: '/matchups/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdRoute = TournamentsTournamentIdRouteImport.update({
  id: '/tournaments/$tournamentId',
  path: '/tournaments/$tournamentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentsTournamentIdRoute =
  AdminTournamentsTournamentIdRouteImport.update({
    id: '/admin/tournaments/$tournamentId',
    path: '/admin/tournaments/$tournamentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedAuthErrorRoute = ProtectedAuthErrorRouteImport.update({
  id: '/_protected/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAuthConfirmRoute = ProtectedAuthConfirmRouteImport.update({
  id: '/_protected/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProtectedProtectedRoute =
  ProtectedProtectedProtectedRouteImport.update({
    id: '/_protected/_protected/protected',
    path: '/protected',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/matchups/': typeof MatchupsIndexRoute
  '/sign-up-success/': typeof SignUpSuccessIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/update-password/': typeof UpdatePasswordIndexRoute
  '/protected': typeof ProtectedProtectedProtectedRoute
  '/auth/confirm': typeof ProtectedAuthConfirmRoute
  '/auth/error': typeof ProtectedAuthErrorRoute
  '/admin/tournaments/$tournamentId': typeof AdminTournamentsTournamentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/login': typeof LoginIndexRoute
  '/matchups': typeof MatchupsIndexRoute
  '/sign-up-success': typeof SignUpSuccessIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/update-password': typeof UpdatePasswordIndexRoute
  '/protected': typeof ProtectedProtectedProtectedRoute
  '/auth/confirm': typeof ProtectedAuthConfirmRoute
  '/auth/error': typeof ProtectedAuthErrorRoute
  '/admin/tournaments/$tournamentId': typeof AdminTournamentsTournamentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/matchups/': typeof MatchupsIndexRoute
  '/sign-up-success/': typeof SignUpSuccessIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/update-password/': typeof UpdatePasswordIndexRoute
  '/_protected/_protected/protected': typeof ProtectedProtectedProtectedRoute
  '/_protected/auth/confirm': typeof ProtectedAuthConfirmRoute
  '/_protected/auth/error': typeof ProtectedAuthErrorRoute
  '/admin/tournaments/$tournamentId': typeof AdminTournamentsTournamentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tournaments/$tournamentId'
    | '/account/'
    | '/admin/'
    | '/forgot-password/'
    | '/login/'
    | '/matchups/'
    | '/sign-up-success/'
    | '/sign-up/'
    | '/tournaments/'
    | '/update-password/'
    | '/protected'
    | '/auth/confirm'
    | '/auth/error'
    | '/admin/tournaments/$tournamentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tournaments/$tournamentId'
    | '/account'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/matchups'
    | '/sign-up-success'
    | '/sign-up'
    | '/tournaments'
    | '/update-password'
    | '/protected'
    | '/auth/confirm'
    | '/auth/error'
    | '/admin/tournaments/$tournamentId'
  id:
    | '__root__'
    | '/'
    | '/tournaments/$tournamentId'
    | '/account/'
    | '/admin/'
    | '/forgot-password/'
    | '/login/'
    | '/matchups/'
    | '/sign-up-success/'
    | '/sign-up/'
    | '/tournaments/'
    | '/update-password/'
    | '/_protected/_protected/protected'
    | '/_protected/auth/confirm'
    | '/_protected/auth/error'
    | '/admin/tournaments/$tournamentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TournamentsTournamentIdRoute: typeof TournamentsTournamentIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MatchupsIndexRoute: typeof MatchupsIndexRoute
  SignUpSuccessIndexRoute: typeof SignUpSuccessIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  UpdatePasswordIndexRoute: typeof UpdatePasswordIndexRoute
  ProtectedProtectedProtectedRoute: typeof ProtectedProtectedProtectedRoute
  ProtectedAuthConfirmRoute: typeof ProtectedAuthConfirmRoute
  ProtectedAuthErrorRoute: typeof ProtectedAuthErrorRoute
  AdminTournamentsTournamentIdRoute: typeof AdminTournamentsTournamentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password/': {
      id: '/update-password/'
      path: '/update-password'
      fullPath: '/update-password/'
      preLoaderRoute: typeof UpdatePasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up-success/': {
      id: '/sign-up-success/'
      path: '/sign-up-success'
      fullPath: '/sign-up-success/'
      preLoaderRoute: typeof SignUpSuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchups/': {
      id: '/matchups/'
      path: '/matchups'
      fullPath: '/matchups/'
      preLoaderRoute: typeof MatchupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId': {
      id: '/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments/$tournamentId': {
      id: '/admin/tournaments/$tournamentId'
      path: '/admin/tournaments/$tournamentId'
      fullPath: '/admin/tournaments/$tournamentId'
      preLoaderRoute: typeof AdminTournamentsTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/auth/error': {
      id: '/_protected/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof ProtectedAuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/auth/confirm': {
      id: '/_protected/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof ProtectedAuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_protected/protected': {
      id: '/_protected/_protected/protected'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof ProtectedProtectedProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TournamentsTournamentIdRoute: TournamentsTournamentIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MatchupsIndexRoute: MatchupsIndexRoute,
  SignUpSuccessIndexRoute: SignUpSuccessIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  UpdatePasswordIndexRoute: UpdatePasswordIndexRoute,
  ProtectedProtectedProtectedRoute: ProtectedProtectedProtectedRoute,
  ProtectedAuthConfirmRoute: ProtectedAuthConfirmRoute,
  ProtectedAuthErrorRoute: ProtectedAuthErrorRoute,
  AdminTournamentsTournamentIdRoute: AdminTournamentsTournamentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
